version: '3'

services:
  constellio:
    image: lracicot/constellio:latest
    # build: .
    links:
      - solr
    environment:
      - SOLR_URL=http://solr:8983/solr
      - ADMIN_SERVICE_KEY=adminkey
      - ADMIN_PASSWORD=password
    ports:
      - 80:8080
    volumes:
      - ./docker/conf:/opt/constellio/conf
      - ./volumes/constellio/contents:/opt/constellio/contents
      - ./volumes/constellio/logs:/opt/constellio/logs
      - ./volumes/constellio/transaction_log:/opt/constellio/transaction_log
      - ./volumes/constellio/work:/opt/constellio/work

  solr:
    build:
      context: .
      dockerfile: Dockerfile.solr
    volumes:
      - ./volumes/solr/records:/opt/solr/server/solr/configsets/records_configs/data
      - ./volumes/solr/notifications:/opt/solr/server/solr/configsets/notifications_configs/data
      - ./volumes/solr/events:/opt/solr/server/solr/configsets/events_configs/data
    ports:
      - 8983:8983
