#!/bin/sh
WAITER_FILE="/opt/constellio/waitforsolr"
CONSTELLIO_FILE="/opt/constellio/conf/constellio.properties"
STARTUP_FILE="/opt/constellio/conf/constellio.setup.properties"

[ ! -z "${SOLR_URL}" ] && sed -i "s@!SOLR_URL!@${SOLR_URL}@" $WAITER_FILE
[ ! -z "${SOLR_URL}" ] && sed -i "s@!SOLR_URL!@${SOLR_URL}@" $CONSTELLIO_FILE
[ ! -z "${ADMIN_SERVICE_KEY}" ] && sed -i "s@!ADMIN_SERVICE_KEY!@${ADMIN_SERVICE_KEY}@" $STARTUP_FILE
[ ! -z "${ADMIN_PASSWORD}" ] && sed -i "s@!ADMIN_PASSWORD!@${ADMIN_PASSWORD}@" $STARTUP_FILE

exec "$@"
